spring:
  application:
    name: activity-service


  mongodb:
    host: localhost
    port: 27017
    database: fitness_activity
#      uri: mongodb://localhost/fitness_activity
#      database: fitness_activity

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/